# Generated by Django 3.2 on 2021-06-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210629_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salay',
            field=models.IntegerField(null=True),
        ),
    ]
