# Generated by Django 3.2 on 2021-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_employee_salay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
