# Generated by Django 3.2 on 2021-06-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_employee_salay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salay',
            new_name='salary',
        ),
    ]
